import { createWayAuthNext } from "@way/auth-sdk/next";

function normalizeBaseUrl(rawValue: string, envKey: string): string {
  const trimmed = rawValue.trim();
  if (!trimmed) {
    return "";
  }

  let parsed: URL;
  try {
    parsed = new URL(trimmed);
  } catch {
    throw new Error(`${envKey} must be a valid URL.`);
  }

  if (!/^https?:$/.test(parsed.protocol)) {
    throw new Error(`${envKey} must use http or https.`);
  }

  if (parsed.pathname !== "/" || parsed.search || parsed.hash) {
    throw new Error(`${envKey} must be an origin only (no path/query/hash).`);
  }

  return parsed.origin;
}

// Generated by way-auth-setup --framework next --minimal and adapted for strict env normalization.
const hasPublicBaseUrl = Boolean(process.env.NEXT_PUBLIC_WAY_AUTH_BASE_URL);
const selectedEnvKey =
  hasPublicBaseUrl || typeof window !== "undefined"
    ? "NEXT_PUBLIC_WAY_AUTH_BASE_URL"
    : "WAY_AUTH_BASE_URL";

const rawWayAuthBaseUrl =
  process.env.NEXT_PUBLIC_WAY_AUTH_BASE_URL ??
  (typeof window === "undefined" ? process.env.WAY_AUTH_BASE_URL : undefined) ??
  "";

const wayAuthBaseUrl = normalizeBaseUrl(rawWayAuthBaseUrl, selectedEnvKey);

if (!wayAuthBaseUrl) {
  throw new Error(
    "WAY Auth base URL is required. Set NEXT_PUBLIC_WAY_AUTH_BASE_URL (and optionally WAY_AUTH_BASE_URL for server fallback).",
  );
}

export const auth = createWayAuthNext({
  baseUrl: wayAuthBaseUrl,
  clientCredentials: "include",
  // Force same-origin auth transport (BFF/proxy mode) even when discovery
  // returns absolute upstream URLs.
  endpoints: {
    signup: "/api/v1/signup",
    login: "/api/v1/login",
    refresh: "/api/v1/refresh",
    logout: "/api/v1/logout",
    me: "/api/v1/me",
    jwks: "/api/v1/jwks",
  },
});

export const wayAuthMiddleware = auth.middleware;
export const wayAuthMatcher = auth.matcher;
