import { createWayAuthNext } from "@way/auth-sdk/next";

// Generated by way-auth-setup --framework next --minimal
const rawWayAuthBaseUrl =
  process.env.NEXT_PUBLIC_WAY_AUTH_BASE_URL ?? process.env.WAY_AUTH_BASE_URL ?? "";
const wayAuthBaseUrl = rawWayAuthBaseUrl.replace(/\/+$/, "");

if (!wayAuthBaseUrl) {
  throw new Error(
    "WAY Auth base URL is required. Set NEXT_PUBLIC_WAY_AUTH_BASE_URL (and WAY_AUTH_BASE_URL for server/middleware).",
  );
}

export const auth = createWayAuthNext({
  baseUrl: wayAuthBaseUrl,
});

export const wayAuthMiddleware = auth.middleware;
export const wayAuthMatcher = auth.matcher;
